### ISSUE TITLE
Rails 5?

### ISSUE THREAD

**Issue by jakehockey10** [maxivak/sortable_tree_rails#2]
Any chance this could work in rails 5?  I notice the gemspec specifies one rails version in particular.

**Comment by maxivak** [comment]
It specifies version >=4.2 so it should work with 4.2.x.
I didn't check the gem with Rails 5.

**Comment by maxivak** [comment]
It might work with Rails 5 since it is based on jquery and acestry gems.

**Comment by danmitchell-** [comment]
I can confirm that this gem works on Rails 5. This issue can be closed.
