### ISSUE TITLE
Not working with rails 5

### ISSUE THREAD

**Issue by oystersauce8** [maxivak/sortable_tree_rails#6]
I was happy to see an earlier comment that this works with rails 5.

My Gemfile looks like this:
`gem 'sortable_tree_rails', github: 'maxivak/sortable_tree_rails'`

The rendering aspects work, but when I try to save to DB, I get

`
Started POST "/categories/sort" for 127.0.0.1 at 2017-05-01 11:27:43 -0700
Processing by CategoriesController#sort as */*
  Parameters: {"cat"=>{"1"=>"null", "2"=>"1", "4"=>"1", "3"=>"null"}}
Completed 500 Internal Server Error in 4ms (ActiveRecord: 0.0ms)

  
NoMethodError (undefined method `inject' for #<ActionController::Parameters:0x007fe339e86ce0>
Did you mean?  inspect):
  
/Users/oystersauce8/.rvm/gems/ruby-2.3.0/bundler/gems/sortable_tree_rails-4666d477c4cc/app/controllers/sortable_tree_controller.rb:22:in `block in sortable_tree'
`

From what I read on the interwebs (https://github.com/arsduo/koala/issues/546), the inject() method is removed from rails 5.1 onwards, but this gem tries to use it.

**Comment by oystersauce8** [comment]
Got past the errror with this dirty hack:
replace `.inject({})`
with `to_unsafe_h.inject({})`
in 
`/Users/johndoe/.rvm/gems/ruby-2.4.1/bundler/gems/sortable_tree_rails-4666d477c4cc/app/controllers/sortable_tree_controller.rb`

**Comment by wvengen** [comment]
@maxivak would you be interested in releasing a new version if a PR would be submitted that fixes this? Not sure if I'll actually do it, but if so, I would consider.

**Comment by maxivak** [comment]
I am looking into it. Do you have fix suggested by @oystersauce8 ?

**Comment by wvengen** [comment]
Great to hear you're looking into it. Will try!

**Comment by maxivak** [comment]
I published the new version 0.0.6 with update for Rails 5.1.

**Comment by wvengen** [comment]
Wow, thanks a lot!
