### ISSUE TITLE
Error "no implicit conversion of nil into String" without controls

### ISSUE THREAD

**Issue by wvengen** [maxivak/sortable_tree_rails#7]
When the controller option `controls_partial` is set to `nil`, rendering gives the error _no implicit conversion of nil into String_ in [`SortableTreeHelper#sortable_tree_render_nested_groups`](https://github.com/maxivak/sortable_tree_rails/blob/4ec0129f0eb964225e73deaf76376118d5d3dde4/app/helpers/sortable_tree_helper.rb#L20).

This happens because `sortable_tree_build_actions(item, opts)` returns `nil`. My suggestion would be to either use string substitution or Ruby methods to build the HTML:

```ruby
s = content_tag(:div, {class: 'item'}) do
  content_tag(:h3, title, {class: "cell left"}) \
  + content_tag(:div, sortable_tree_build_actions(item, opts), {class: "cell right controls"})
end
```

**Comment by wvengen** [comment]
Note that the possibity to pass `nil` to `controls_partial` is [documented](https://github.com/maxivak/sortable_tree_rails#options-for-controller) in the README.

**Comment by wvengen** [comment]
Apparently this is a view option, not a controller option (but default `nil` so it happens by default).

**Comment by maxivak** [comment]
fixed for the case when option :controls_partial is not set.
see version 0.0.7 of gem.

**Comment by maxivak** [comment]
updated documentation. the option :controls_partial must be in view, not in controller.

**Comment by wvengen** [comment]
:+1: :smiley:
