### ISSUE TITLE
JS: ReferenceError: $ is not defined

### ISSUE THREAD

**Issue by wvengen** [maxivak/sortable_tree_rails#8]
In my default Rails setup, scripts are loaded after the whole page is rendered. This speeds up page load, and is in line with [progressive enhancement](https://en.wikipedia.org/wiki/Progressive_enhancement).

This gem puts javascript in the web body of the page, assuming that jQuery was loaded. This is not the case when scripts are loaded last.
I do not see any substitution taking place in the Javascript, so I suggest to put it in a separate file, so that it can be picked up by the asset pipeline and gets injected in the right place.

**Comment by wvengen** [comment]
Hmm, `max_levels` is injected as an option.
This can be set as a data-attribute on the `sortable-tree` element and picked up from there.

**Comment by maxivak** [comment]
the gem includes a separate javascript file 'jquery.mjs.nestedSortable.js'.

So you can include it in your assets.

In basic example your application.js would be:
```
//= require jquery2
//= require jquery-ui

//=require jquery.mjs.nestedSortable.js

```

**Comment by maxivak** [comment]
or you mean to have this js code in a separate file?

```

:javascript
  $(document).ready(function(){
    $('.sortable_tree').nestedSortable({
   ...
});

...
```

**Comment by wvengen** [comment]
Yes!

**Comment by maxivak** [comment]
in new version 0.0.8:
- a separate file to include in assets
```
//=require sortable_tree.js
```
- option :max_levels is passed via data attribute, but it doesn't influence the usage.
it is the same:
```
= render_sortable_tree(@items, {name_method: :name, sort_url: sort_categories_url, max_levels: 5, controls_partial: 'controls'})
```

see readme.

**Comment by wvengen** [comment]
Yes, that works! Thanks :fireworks:
