### ISSUE TITLE
Make sorting optional

### ISSUE THREAD

**Issue by wvengen** [maxivak/sortable_tree_rails#9]
Ancestry does not do sorting by default, and this gem currently requires the presence of a sorting attribute.
Could the sorting become optional (e.g. by setting `sorting_attribute` to `nil`)? Then only the hierarchy would be updated but not the `pos` attribute (or whetever is configured).

**Comment by maxivak** [comment]
Updated in v. 0.0.9.
see the doc

* Example. For model with ancestry.
If you use ancestry in model - set :parent_method to 'parent'.

```
  include SortableTreeController::Sort
  sortable_tree 'ClassName', {parent_method: 'parent', sorting_attribute: 'pos'}
```

* Example. Do only sorting, without tree.

```
  include SortableTreeController::Sort
  sortable_tree 'ClassName', {sorting_attribute: 'pos', parent_method: nil}
```

* Example. No sorting, update only parent.

```
  include SortableTreeController::Sort
  sortable_tree 'ClassName', {sorting_attribute: nil, parent_method: 'parent'}
```
